# -*- coding: utf-8 -*-
"""tables_creator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNgoSiw1UfEQk5Zt3W1iLKyeizSSIPSg
"""

import numpy as np
import pandas as pd
import re
from pathlib import Path

# =======================
# SETTINGS (CHANGE THESE)
# =======================
INPUT_CSV = "/home/sergey/Desktop/Project/car_data.csv"
PROJECT_FOLDER_NAME = "/home/sergey/Desktop/Project"
OUTPUT_SUBFOLDER = "out_tables"

# =======================
# HELPERS
# =======================
def normalize_text(x):
    if pd.isna(x):
        return None
    s = str(x).strip()
    return s if s != "" else None

def parse_bool(x):
    """
    Converts common formats to boolean.
    Unknown -> None
    """
    if pd.isna(x):
        return None
    s = str(x).strip().lower()
    if s in {"true", "1", "yes", "y", "այո"}:
        return True
    if s in {"false", "0", "no", "n", "ոչ"}:
        return False
    return None

def parse_numeric(x):
    """
    Converts values like '1,200,000 AMD' '$12,500' '12 500' -> float
    Unknown -> NaN
    """
    if pd.isna(x):
        return np.nan
    s = str(x).replace(",", "").replace(" ", "")
    cleaned = "".join(ch for ch in s if ch.isdigit() or ch in {".", "-"})
    if cleaned in {"", "-", ".", "-."}:
        return np.nan
    try:
        return float(cleaned)
    except:
        return np.nan

def url_to_listing_id(url: str):
    """
    Extracts numeric ID from list.am item URL.
    Example:
    https://www.list.am/en/item/20250584 -> 20250584
    """
    if pd.isna(url):
        return None
    m = re.search(r"/item/(\d+)", str(url))
    if m:
        return int(m.group(1))
    return None

# =======================
# OUTPUT PATH (Linux Desktop)
# =======================
desktop_path = Path.home() / "Desktop"
project_path = desktop_path / PROJECT_FOLDER_NAME
out_dir = project_path / OUTPUT_SUBFOLDER
out_dir.mkdir(parents=True, exist_ok=True)

# =======================
# LOAD DATA
# =======================
df = pd.read_csv(INPUT_CSV)
df.columns = [c.strip() for c in df.columns]

if "url" not in df.columns:
    raise ValueError("CSV-ում 'url' սյուն չկա։ Ստուգիր քո ֆայլի header-ը։")

# Clean & dedupe URL
df["url"] = df["url"].apply(normalize_text)
df = df.dropna(subset=["url"]).drop_duplicates(subset=["url"]).reset_index(drop=True)

# Create listing_id from URL number
df["listing_id"] = df["url"].apply(url_to_listing_id)

# Drop rows where ID not extracted (not matching list.am structure)
df = df.dropna(subset=["listing_id"]).copy()
df["listing_id"] = df["listing_id"].astype("int64")

# Ensure listing_id is unique (it should be if URL unique)
df = df.drop_duplicates(subset=["listing_id"]).reset_index(drop=True)

# Normalize common text columns (if exist)
text_cols = [
    "make", "model", "engine_type", "transmission", "drive_type",
    "steering_wheel", "body_type", "color", "interior_material",
    "condition", "comfort"
]
for c in text_cols:
    if c in df.columns:
        df[c] = df[c].apply(normalize_text)

# Parse booleans
for c in ["sunroof", "cleared_customs"]:
    if c in df.columns:
        df[c] = df[c].apply(parse_bool)

# Parse numerics
for c in ["price", "mileage", "engine_size", "wheel_size", "year"]:
    if c in df.columns:
        df[c] = df[c].apply(parse_numeric)

# Convert year/mileage to nullable ints (optional)
if "year" in df.columns:
    df["year"] = pd.to_numeric(df["year"], errors="coerce").round().astype("Int64")
if "mileage" in df.columns:
    df["mileage"] = pd.to_numeric(df["mileage"], errors="coerce").round().astype("Int64")

# =======================
# BUILD 6 TABLES
# =======================
listing_core = df[["listing_id", "url"]].copy()

listing_pricing = df.reindex(columns=["listing_id", "price", "year", "mileage"]).copy()

listing_vehicle = df.reindex(columns=["listing_id", "make", "model"]).copy()

listing_specs = df.reindex(columns=[
    "listing_id", "engine_size", "engine_type", "transmission", "drive_type",
    "steering_wheel", "wheel_size", "comfort"
]).copy()

listing_appearance = df.reindex(columns=[
    "listing_id", "body_type", "color", "interior_material", "sunroof"
]).copy()

listing_status = df.reindex(columns=[
    "listing_id", "cleared_customs", "condition"
]).copy()

# =======================
# SAVE AS CSV
# =======================
listing_core.to_csv(out_dir / "core.csv", index=False)
listing_pricing.to_csv(out_dir / "pricing.csv", index=False)
listing_vehicle.to_csv(out_dir / "vehicle.csv", index=False)
listing_specs.to_csv(out_dir / "specs.csv", index=False)
listing_appearance.to_csv(out_dir / "appearance.csv", index=False)
listing_status.to_csv(out_dir / "status.csv", index=False)

# =======================
# SUMMARY PRINT
# =======================
print("Պատրաստ է ✅")
print(f"Տողերի քանակը (unique listings): {len(df)}")
print("Ֆայլերը պահպանվել են այստեղ 👇")
print(out_dir.resolve())
print("\nՍտացված ֆայլերը՝")
for p in sorted(out_dir.glob("*.csv")):
    print("-", p.name)